import { _electron as electron, expect } from '@playwright/test';
import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import path from 'node:path';
const root = process.cwd();
const data = path.join(root, '.test-data', `desktop-${Date.now()}`);
mkdirSync(data, { recursive: true });
mkdirSync(path.join(root, 'test-results'), { recursive: true });
const env = { ...process.env, SAKLI_DATA_DIR: data }; delete env.ELECTRON_RUN_AS_NODE;
const exe = process.env.SAKLI_TEST_EXE;
const launch = () => electron.launch({ ...(exe ? { executablePath: exe, args: [] } : { args: ['.'] }), cwd: root, env });
let app = await launch();
const errors = [];
try {
  let page = await app.firstWindow();
  page.on('pageerror', e => errors.push(e.message));
  await page.waitForLoadState('networkidle');
  await expect(page).toHaveTitle('DubBitig — Kişisel arşivin');
  await expect(page.getByAltText('DubBitig logosu')).toBeVisible();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await expect(page.getByRole('heading', { name: 'Tüm kayıtlar' })).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Her şey bir kayıtla başlar' })).toBeVisible();
  await page.screenshot({ animations: 'disabled', path: 'test-results/empty.png' });
  await page.getByRole('button', { name: 'Yeni kayıt' }).click();
  await page.getByRole('group', { name: 'Kayıt türü' }).getByRole('button', { name: 'Komut', exact: true }).click();
  await page.getByRole('textbox', { name: 'Başlık' }).fill('Çalışan işlemleri listele');
  await page.getByRole('textbox', { name: 'Açıklama' }).fill('PowerShell ile çalışan işlemleri bellek kullanımına göre göster.');
  await page.getByRole('textbox', { name: 'Komut' }).fill('Get-Process | Sort-Object WorkingSet -Descending');
  await page.getByRole('combobox', { name: 'Kategori', exact: true }).fill('Windows');
  await page.getByRole('textbox', { name: 'Etiketler' }).fill('powershell, sistem');
  await page.getByRole('button', { name: 'Kaydet', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Çalışan işlemleri listele' })).toBeVisible();
  await page.getByRole('button', { name: 'Çalışan işlemleri listele kopyala', exact: true }).click();
  const clipboard = await app.evaluate(({ clipboard }) => clipboard.readText());
  expect(clipboard).toBe('Get-Process | Sort-Object WorkingSet -Descending');
  await page.getByRole('button', { name: 'Çalışan işlemleri listele favorilere ekle' }).click();
  await page.getByRole('textbox', { name: 'Arşivde ara' }).fill('calisan');
  await expect(page.getByRole('heading', { name: 'Çalışan işlemleri listele' })).toBeVisible();
  await page.getByRole('textbox', { name: 'Arşivde ara' }).fill('bulunmayan123');
  await expect(page.getByRole('heading', { name: 'Eşleşen kayıt bulunamadı' })).toBeVisible();
  await page.getByRole('button', { name: 'Aramayı temizle' }).click();

  // Create varied real test records through the same isolated IPC bridge.
  await page.evaluate(async () => {
    const base = { description: '', content: '', url: '', tags: [], category: '', favorite: false, assets: [] };
    await window.sakli.save({ ...base, title: 'Haftalık çalışma notları', kind: 'note', description: 'Bu hafta üzerinde çalışacağım konular ve aklımda kalanlar.', content: 'Yedekleri kontrol et.\nArşivi düzenle.\nYeni proje fikirlerini not al.', category: 'Günlük yaşam', tags: ['plan', 'kişisel'] });
    await window.sakli.save({ ...base, title: 'MDN Web Docs', kind: 'link', description: 'Web geliştirme için başvuru kaynağı.', url: 'https://developer.mozilla.org/', category: 'Geliştirme', tags: ['dokümantasyon', 'web'] });
    await window.sakli.save({ ...base, title: 'Visual Studio Code', kind: 'program', description: 'Projeleri ve notları düzenlemek için kod editörü.', url: 'https://code.visualstudio.com/', content: 'Ctrl + Shift + P: Komut paletini aç.', category: 'Geliştirme', tags: ['editör', 'araçlar'] });
  });
  const photoPath = path.join(data, 'deneme.png');
  writeFileSync(photoPath, Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAwMCAO+jRZkAAAAASUVORK5CYII=', 'base64'));
  await app.evaluate(({ dialog }, photoPath) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [photoPath] }); }, photoPath);
  await page.getByRole('button', { name: 'Yeni kayıt' }).click();
  await page.getByRole('group', { name: 'Kayıt türü' }).getByRole('button', { name: 'Fotoğraf', exact: true }).click();
  await page.getByRole('textbox', { name: 'Başlık' }).fill('Fotoğraf testi');
  await page.getByRole('button', { name: 'Fotoğraf ekle', exact: true }).click();
  await expect(page.getByAltText('deneme.png')).toBeVisible();
  await page.getByRole('button', { name: 'Kaydet', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Fotoğraf testi' })).toBeVisible();
  await page.getByRole('button', { name: 'Çalışan işlemleri listele kaydını aç' }).click();
  await expect(page.getByRole('button', { name: 'Düzenle', exact: true })).toBeVisible();
  await page.locator('.content-area').evaluate(el => { el.scrollTop = 0; });
  await page.screenshot({ animations: 'disabled', path: 'test-results/archive.png' });
  await page.getByRole('button', { name: 'Açık', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await page.screenshot({ animations: 'disabled', path: 'test-results/archive-light.png' });
  await page.getByRole('button', { name: 'Koyu', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  await page.getByRole('button', { name: 'Düzenle', exact: true }).click();
  await page.getByRole('textbox', { name: 'Başlık' }).fill('İşlem listesini görüntüle');
  await page.getByRole('button', { name: 'Kaydet', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'İşlem listesini görüntüle', exact: true }).first()).toBeVisible();
  await page.getByRole('button', { name: 'Kaydı sil', exact: true }).click();
  await page.getByRole('button', { name: 'Çöp kutusuna taşı', exact: true }).click();
  await page.getByRole('button', { name: /^Çöp kutusu/ }).click();
  await page.getByRole('button', { name: 'İşlem listesini görüntüle geri al' }).click();
  await page.getByRole('button', { name: /^Tüm kayıtlar/ }).click();
  await expect(page.getByRole('heading', { name: 'İşlem listesini görüntüle' })).toBeVisible();
  await page.getByRole('button', { name: 'Kategorileri yönet' }).click();
  await page.getByRole('textbox', { name: 'Yeni kategori adı' }).fill('Belgeler');
  await page.getByRole('button', { name: 'Ekle', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Belgeler yeniden adlandır' })).toBeVisible();
  await page.getByRole('button', { name: 'Belgeler yeniden adlandır' }).click();
  await page.getByRole('textbox', { name: 'Kategori adı', exact: true }).fill('Kaynaklar');
  await page.getByRole('button', { name: 'Kategori adını kaydet' }).click();
  await expect(page.getByRole('button', { name: 'Kaynaklar yeniden adlandır' })).toBeVisible();
  await page.getByRole('button', { name: 'Pencereyi kapat' }).click();
  await page.getByRole('combobox', { name: 'Kayıt sıralaması' }).selectOption('oldest');
  await expect(page.locator('.entry-card h3').first()).toHaveText('İşlem listesini görüntüle');
  await page.getByRole('combobox', { name: 'Etikete göre filtrele' }).selectOption('sistem');
  await expect(page.locator('.entry-card')).toHaveCount(1);
  await page.getByRole('button', { name: 'Filtreleri temizle' }).click();

  const exported = path.join(data, 'aktarim.sakli');
  await app.evaluate(({ dialog }, exported) => { dialog.showSaveDialog = async () => ({ canceled: false, filePath: exported }); }, exported);
  await page.getByRole('button', { name: 'Dışarı aktar', exact: true }).click();
  await page.getByRole('button', { name: 'Dosyaya aktar', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('dışarı aktarıldı');
  expect(existsSync(exported)).toBe(true);
  await app.evaluate(({ dialog }, exported) => { dialog.showOpenDialog = async () => ({ canceled: false, filePaths: [exported] }); }, exported);
  await page.getByRole('button', { name: 'İçeri aktar', exact: true }).click();
  await page.getByRole('button', { name: 'Dosya seç ve aktar', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('0 kayıt');
  // Category export includes only active records and referenced photos in that category.
  await page.getByRole('button', { name: 'Dışarı aktar', exact: true }).click();
  await page.getByRole('button', { name: /Kategorileri dışa aktar/ }).click();
  await page.getByRole('checkbox', { name: 'Windows kategorisini aktar' }).check();
  await expect(page.getByText('1 kayıt ve 0 fotoğraf')).toBeVisible();
  await page.screenshot({ animations: 'disabled', path: 'test-results/category-transfer.png' });
  await page.getByRole('button', { name: 'Dosyaya aktar', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('Seçilen kategoriler dışarı aktarıldı');
  await page.getByRole('button', { name: 'İçeri aktar', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Hedef kategoriye yeni kopyalar ekle' }).check();
  await page.getByRole('combobox', { name: 'Hedef kategori' }).selectOption('Kaynaklar');
  await page.getByRole('button', { name: 'Dosya seç ve aktar', exact: true }).click();
  await expect(page.getByRole('status')).toContainText('1 kayıt');
  const transferred = await page.evaluate(() => window.sakli.snapshot());
  expect(transferred.entries.filter(e => e.category === 'Windows')).toHaveLength(1);
  expect(transferred.entries.filter(e => e.category === 'Kaynaklar')).toHaveLength(1);
  // Remove a selected category without deleting its records or leaving a stale filter.
  await expect(page.locator('.sidebar .category-nav')).toHaveCount(0);
  await page.getByRole('button', { name: 'Kategorileri yönet' }).click();
  await page.getByRole('button', { name: 'Kaynaklar kayıtlarını göster' }).click();
  await page.getByRole('button', { name: 'Kategorileri yönet' }).click();
  await page.getByRole('button', { name: 'Kaynaklar kategorisini kaldır' }).click();
  await page.getByRole('button', { name: 'Kategoriyi kaldır', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Kaynaklar kategorisini kaldır' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Pencereyi kapat' }).click();
  await expect(page.getByRole('heading', { name: 'Tüm kayıtlar', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Etiketleri yönet', exact: true }).click();
  await page.getByRole('textbox', { name: 'Yeni etiket adı' }).fill('sonra');
  await page.getByRole('button', { name: 'Ekle', exact: true }).click();
  await page.getByRole('button', { name: 'sistem yeniden adlandır' }).click();
  await page.getByRole('textbox', { name: 'Etiket adı', exact: true }).fill('sistemler');
  await page.getByRole('button', { name: 'Etiket adını kaydet' }).click();
  await page.getByRole('button', { name: 'sistemler etiketini kaldır' }).click();
  await page.screenshot({ animations: 'disabled', path: 'test-results/tag-management.png' });
  await page.getByRole('button', { name: 'Etiketi kaldır', exact: true }).click();
  await expect(page.getByRole('button', { name: 'sistemler etiketini kaldır' })).toHaveCount(0);
  await page.getByRole('button', { name: 'Pencereyi kapat' }).click();
  const managed = await page.evaluate(() => window.sakli.snapshot());
  expect(managed.entries).toHaveLength(transferred.entries.length);
  expect(managed.categories).not.toContain('Kaynaklar');
  expect(managed.entries.some(e => e.tags.includes('sistemler') || e.tags.includes('sistem'))).toBe(false);
  expect(managed.tags).toContain('sonra');
  await page.getByRole('button', { name: 'İşlem listesini görüntüle kaydını aç' }).first().click();
  await page.getByRole('button', { name: 'Düzenle', exact: true }).click();
  await page.getByRole('button', { name: 'powershell etiketini kayıttan kaldır' }).click();
  await page.getByRole('button', { name: 'sonra etiketini kayda ekle' }).click();
  await page.getByRole('button', { name: 'Kaydet', exact: true }).click();
  await page.getByRole('button', { name: 'Ayrıntıları kapat' }).click();
  await page.getByRole('button', { name: 'Ayarlar ve yedekler', exact: true }).click();
  await page.getByRole('button', { name: 'Şimdi yedekle', exact: true }).click();
  await page.getByRole('combobox', { name: 'Yedekleme sıklığı' }).selectOption('weekly');
  await expect(page.getByRole('combobox', { name: 'Yedekleme sıklığı' })).toHaveValue('weekly');
  await page.getByRole('tab', { name: 'Genel', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Arka planda bağlantı denetimi' }).uncheck();
  await page.getByRole('tab', { name: 'Yedekleme', exact: true }).click();
  await expect(page.getByText('elle alınan yedek', { exact: false }).first()).toBeVisible();
  await app.evaluate(({ dialog }) => { dialog.showMessageBox = async () => ({ response: 1, checkboxChecked: false }); });
  await page.getByRole('button', { name: 'Geri yükle', exact: true }).first().click();
  await expect(page.getByRole('status')).toContainText('Yedek geri yüklendi');
  await page.screenshot({ animations: 'disabled', path: 'test-results/settings.png' });
  await page.getByRole('button', { name: 'Pencereyi kapat' }).click();
  await page.getByRole('button', { name: 'Açık', exact: true }).click();
  await page.getByRole('button', { name: 'Liste görünümü' }).click();
  await expect(page.locator('.entries.list')).toBeVisible();
  await app.evaluate(({ BrowserWindow }) => BrowserWindow.getAllWindows()[0].setSize(980, 740));
  await page.screenshot({ animations: 'disabled', path: 'test-results/compact.png' });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await app.close();
  app = await launch(); page = await app.firstWindow();
  await expect(page.getByRole('heading', { name: 'İşlem listesini görüntüle' }).first()).toBeVisible();
  await expect(page.getByRole('heading', { name: 'Fotoğraf testi' })).toBeVisible();
  await expect(page.getByAltText('deneme.png')).toBeVisible();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'light');
  await page.getByRole('button', { name: 'Koyu', exact: true }).click();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark');
  expect((await page.evaluate(() => window.sakli.settings())).backupPeriod).toBe('weekly');
  // Revision UI restores content while preserving taxonomy and saves the current revision.
  await page.getByRole('button', { name: 'İşlem listesini görüntüle kaydını aç' }).first().click();
  await page.getByRole('button', { name: /Sürüm geçmişi/ }).click();
  await expect(page.getByRole('dialog').getByText('Çalışan işlemleri listele', { exact:true })).toBeVisible();
  await page.screenshot({ animations:'disabled',path:'test-results/history.png' });
  await page.getByRole('button', { name: 'Bu sürümü geri yükle' }).click();
  await page.getByRole('button', { name: 'Geri yüklemeyi onayla' }).click();
  await expect(page.locator('.detail-panel h2')).toHaveText('Çalışan işlemleri listele');
  await page.getByRole('button', { name: 'Düzenle', exact:true }).click();
  await page.getByRole('textbox', { name: 'Başlık' }).fill('Hatırlatma testi');
  await page.getByLabel('Hatırlatma zamanı', { exact:true }).fill('2020-01-31T10:00');
  await page.getByRole('combobox', { name:'Hatırlatma tekrarı' }).selectOption('monthly');
  await page.getByLabel('Son kullanma tarihi', { exact:true }).fill('2020-01-31T10:00');
  await page.screenshot({ animations:'disabled',path:'test-results/reminder-editor.png' });
  await page.getByRole('button', { name:'Kaydet',exact:true }).click();
  await page.getByRole('button', { name:'Ayrıntıları kapat' }).click();
  await app.close(); app=await launch(); page=await app.firstWindow();
  await expect(page.getByRole('button', { name:/^Hatırlatıcılar 2$/ })).toBeVisible();
  await page.getByRole('button', { name:/^Hatırlatıcılar/ }).click();
  await expect(page.getByRole('button',{name:'Okundu',exact:true})).toHaveCount(2);
  await page.screenshot({ animations:'disabled',path:'test-results/reminders.png' });
  await page.getByRole('button',{name:'Okundu',exact:true}).first().click();
  await expect(page.getByRole('button',{name:'Okundu',exact:true})).toHaveCount(1);
  await page.getByRole('button',{name:'Pencereyi kapat'}).click();
  // Use the real preview IPC and native image decoder against a public metadata source.
  await page.getByRole('button',{name:'Yeni kayıt'}).click();
  await page.getByRole('group',{name:'Kayıt türü'}).getByRole('button',{name:'Bağlantı',exact:true}).click();
  await page.getByRole('textbox',{name:'Bağlantı *',exact:true}).fill('https://www.wikipedia.org/');
  await expect(page.getByRole('textbox',{name:'Başlık'})).toHaveValue(/Wikipedia/,{timeout:60000});
  await expect(page.getByRole('dialog').locator('.site-favicon')).toBeVisible({timeout:10000});
  await expect(page.getByRole('dialog').locator('.web-preview-image')).toBeVisible({timeout:10000});
  await page.getByRole('button',{name:'Kaydet',exact:true}).click();
  const wiki = (await page.evaluate(()=>window.sakli.snapshot())).entries.find(e=>e.url==='https://www.wikipedia.org/');
  expect(wiki.preview.favicon).toBeTruthy(); expect(wiki.preview.image).toBeTruthy();
  await page.getByRole('button',{name:`${wiki.title} kaydını aç`,exact:true}).click();
  await page.getByRole('button',{name:'Bağlantıyı denetle',exact:true}).click();
  await expect(page.locator('.detail-panel .link-health')).toContainText('Erişilebilir',{timeout:30000});
  await page.screenshot({animations:'disabled',path:'test-results/web-preview.png'});
  expect(errors).toEqual([]);
  console.log('PASS: desktop CRUD, search, clipboard, photos, backups, category-scoped transfer, persistent light/dark themes, DubBitig branding, layout and persistence.');
  console.log(`Test data: ${data}`);
} finally { await app.close(); }
