import { _electron as electron, expect } from '@playwright/test';
import { mkdirSync, readdirSync } from 'node:fs';
import path from 'node:path';
const data=path.join(process.cwd(),'.test-data',`features15-${Date.now()}`);
mkdirSync(data,{recursive:true});mkdirSync('test-results',{recursive:true});
const env={...process.env,DUBBITIG_DATA_DIR:data};delete env.ELECTRON_RUN_AS_NODE;
const launch=()=>electron.launch({...(process.env.SAKLI_TEST_EXE?{executablePath:process.env.SAKLI_TEST_EXE,args:[]}:{args:['.']}),env});
let app=await launch();const errors=[];
try {
  let page=await app.firstWindow();page.on('pageerror',e=>errors.push(e.message));await page.waitForLoadState('networkidle');
  await page.getByRole('button',{name:'Yeni kayıt'}).click();
  await page.getByRole('textbox',{name:'Başlık'}).fill('Markdown denemesi');
  const markdown='# Çalışma defteri\n\n**Önemli not** ve *küçük ayrıntı*.\n\n- İlk adım\n- İkinci adım\n\n| Komut | Amaç |\n| --- | --- |\n| Get-Process | İşlemler |\n\n```powershell\nGet-Process | Where-Object { $_.CPU -gt 10 }\n```\n\n<script>window.UNSAFE=true</script>\n\n![Uzak görsel](https://example.com/image.png)';
  await page.getByRole('textbox',{name:'İçerik',exact:true}).fill(markdown);
  await page.getByRole('tab',{name:'Önizleme'}).click();
  await expect(page.locator('.editor-rendered h1')).toHaveText('Çalışma defteri');
  await expect(page.locator('.editor-rendered strong')).toHaveText('Önemli not');
  await expect(page.locator('.editor-rendered table')).toBeVisible();
  expect(await page.locator('.editor-rendered .hljs-keyword, .editor-rendered .hljs-built_in, .editor-rendered .hljs-variable').count()).toBeGreaterThan(0);
  await expect(page.locator('.editor-rendered img')).toHaveCount(0);
  expect(await page.evaluate(()=>window.UNSAFE)).toBeUndefined();
  await page.screenshot({path:'test-results/markdown-dark.png',animations:'disabled'});
  await page.getByRole('button',{name:'Kaydet',exact:true}).click();
  await page.getByRole('button',{name:'Markdown denemesi kaydını aç'}).click();
  await expect(page.locator('.detail-panel .markdown-content h1')).toHaveText('Çalışma defteri');
  await page.getByRole('button',{name:'Yeni kayıt'}).click();
  await page.getByRole('group',{name:'Kayıt türü'}).getByRole('button',{name:'Komut',exact:true}).click();
  await page.getByRole('textbox',{name:'Başlık'}).fill('PowerShell komutu');
  await page.getByRole('combobox',{name:'Kod dili'}).selectOption('powershell');
  await page.getByRole('textbox',{name:'Komut'}).fill('Write-Output "Merhaba <script>"');
  await page.getByRole('tab',{name:'Önizleme'}).click();await expect(page.locator('.editor-rendered .hljs-string')).toContainText('Merhaba');
  await page.getByRole('button',{name:'Kaydet',exact:true}).click();
  await page.getByRole('button',{name:'PowerShell komutu kopyala',exact:true}).click();expect(await app.evaluate(({clipboard})=>clipboard.readText())).toBe('Write-Output "Merhaba <script>"');
  expect((await page.evaluate(()=>window.sakli.snapshot())).entries.find(e=>e.kind==='command').language).toBe('powershell');
  await page.getByRole('button',{name:'Açık',exact:true}).click();
  await page.getByRole('button',{name:'Ayarlar ve yedekler',exact:true}).click();
  await page.getByRole('button',{name:'Şimdi yedekle',exact:true}).click();
  await page.getByRole('tab',{name:'Program Bilgi',exact:true}).click();await expect(page.getByText('Dub (Tablet)',{exact:true})).toBeVisible();await expect(page.getByText('Bitig (Yazı)',{exact:true})).toBeVisible();
  await page.screenshot({path:'test-results/about-light.png',animations:'disabled'});
  await page.getByRole('tab',{name:'Veriler',exact:true}).click();
  await page.getByRole('button',{name:'Bütün verileri sil',exact:true}).click();
  await expect(page.getByRole('button',{name:'Kalıcı olarak sil',exact:true})).toBeDisabled();
  await page.getByRole('textbox',{name:'Silme onayı'}).fill('sil');await expect(page.getByRole('button',{name:'Kalıcı olarak sil',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Vazgeç',exact:true}).click();expect((await page.evaluate(()=>window.sakli.snapshot())).entries.length).toBe(2);
  await page.getByRole('button',{name:'Bütün verileri sil',exact:true}).click();await page.getByRole('textbox',{name:'Silme onayı'}).fill('BÜTÜN VERİLERİ SİL');
  await page.screenshot({path:'test-results/delete-confirmation.png',animations:'disabled'});
  await page.getByRole('button',{name:'Kalıcı olarak sil',exact:true}).click();await expect(page.getByRole('status')).toContainText('Bütün yerel veriler silindi');
  expect(await page.evaluate(()=>window.sakli.snapshot())).toEqual({entries:[],categories:[],tags:[]});expect(readdirSync(path.join(data,'photos'))).toEqual([]);expect(await page.evaluate(()=>window.sakli.backups())).toEqual([]);
  await page.getByRole('button',{name:'Pencereyi kapat',exact:true}).click();await expect(page.locator('html')).toHaveAttribute('data-theme','dark');
  await app.close();app=await launch();page=await app.firstWindow();await page.waitForLoadState('networkidle');expect((await page.evaluate(()=>window.sakli.snapshot())).entries).toEqual([]);
  await page.getByRole('button',{name:'Yeni kayıt'}).click();await page.getByRole('textbox',{name:'Başlık'}).fill('Yeni başlangıç');await page.getByRole('textbox',{name:'İçerik',exact:true}).fill('Temiz arşiv');await page.getByRole('button',{name:'Kaydet',exact:true}).click();await expect(page.getByRole('heading',{name:'Yeni başlangıç'})).toBeVisible();
  expect(errors).toEqual([]);console.log('PASS: Markdown/GFM, syntax, safe HTML, exact clipboard, about, typed deletion, backups cleared, restart and new records.');
} finally { await app.close(); }
