import { useCallback, useEffect, useState } from 'react';
import { Database, HardDrive, Info, Settings2, Trash2, FolderOpen, Download, Upload, RotateCcw } from 'lucide-react';
import { Button } from './ui/button';
import { Input } from './ui/input';
import { Badge } from './ui/badge';
import { Tabs, TabsList, TabsTrigger, TabsContent } from './ui/tabs';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from './ui/dialog';
import { getAPI } from '../api';
import type { BackupInfo, BackupPeriod, Settings } from '../shared/model';
const date = (v: string) => new Date(v).toLocaleString('tr-TR');
const errorText = (e: unknown) => String(e).replace(/^Error: Error invoking remote method '[^']+': Error: /, '');
export function SettingsPanel({ close, changed, notify, transfer, reset }: { close: () => void; changed: () => Promise<void>; notify: (v: string,e?: boolean) => void; transfer: (mode:'import'|'export') => void; reset: () => Promise<void> }) {
  const [settings,setSettings] = useState<Settings>(); const [backups,setBackups] = useState<BackupInfo[]>([]); const [busy,setBusy] = useState(false); const [confirm,setConfirm] = useState(false); const [phrase,setPhrase] = useState('');
  const refresh = useCallback(async()=>{ const [s,b] = await Promise.all([getAPI().settings(),getAPI().backups()]);setSettings(s);setBackups(b); },[]);
  useEffect(()=>{void refresh().catch(e=>notify(errorText(e),true));},[refresh,notify]);
  const action = async(fn:()=>Promise<unknown>, text?:string) => {setBusy(true);try{await fn();await refresh();await changed();if(text)notify(text);}catch(e){notify(errorText(e),true);}finally{setBusy(false);}};
  return <Dialog open onOpenChange={open=>{if(!open&&!busy)close();}}><DialogContent className="settings-dialog sm:max-w-3xl max-h-[88dvh] overflow-y-auto"><DialogHeader><DialogTitle>Ayarlar ve yedekler</DialogTitle><DialogDescription>Arşivinin görünümü, güvenliği ve verileri.</DialogDescription></DialogHeader>
    <Tabs defaultValue="backup" className="gap-6"><TabsList className="grid w-full grid-cols-4"><TabsTrigger value="backup"><HardDrive/>Yedekleme</TabsTrigger><TabsTrigger value="general"><Settings2/>Genel</TabsTrigger><TabsTrigger value="data"><Database/>Veriler</TabsTrigger><TabsTrigger value="about"><Info/>Program Bilgi</TabsTrigger></TabsList>
      <TabsContent value="backup" className="space-y-5"><div className="settings-callout"><HardDrive/><div><h3>Bilgini güvenle sakla</h3><p>Kayıtların ve fotoğrafların birlikte yedeklenir.</p></div></div>
        <div className="setting-row"><div><strong>Otomatik yedekleme</strong><p>Değişiklik varsa seçtiğin aralıkta yedeklenir. Son 14 otomatik yedek tutulur.</p></div><label className="switch"><input type="checkbox" aria-label="Otomatik yedekleme" checked={settings?.autoBackup??false} disabled={busy||!settings} onChange={e=>action(()=>getAPI().setAutoBackup(e.target.checked))}/><span/></label></div>
        <div className="setting-row"><label>Yedekleme sıklığı<select aria-label="Yedekleme sıklığı" value={settings?.backupPeriod??'daily'} disabled={busy||!settings} onChange={e=>action(()=>getAPI().setBackupPeriod(e.target.value as BackupPeriod))}><option value="30m">30 dakikada bir</option><option value="daily">Günde bir</option><option value="weekly">Haftada bir</option><option value="monthly">Ayda bir</option></select></label><p className="hint">{settings?.nextBackup?'Sonraki kontrol: '+date(settings.nextBackup):'Uygulama kapalıysa sonraki açılışta kontrol edilir.'}</p></div>
        {settings?.backupError&&<p className="form-error" role="alert">{settings.backupError}</p>}<div className="flex items-center justify-between gap-4"><p className="text-sm text-muted-foreground">Son yedek: {settings?.lastBackup?date(settings.lastBackup):'Henüz yok'}</p><Button disabled={busy} onClick={()=>action(()=>getAPI().backup(),'Yedek oluşturuldu.')}>Şimdi yedekle</Button></div>
        <div className="section-heading"><h3>Bu bilgisayardaki yedekler</h3><Button variant="ghost" size="sm" onClick={()=>action(()=>getAPI().openFolder('backup'))}><FolderOpen/>Klasörü aç</Button></div><div className="backup-list">{backups.map(b=><div key={b.name}><HardDrive size={20}/><span><strong>{date(b.date)}</strong><small>{b.name.endsWith('auto.sakli')?'Otomatik yedek':'Güvenlik / elle alınan yedek'} · {Math.max(1,Math.round(b.size/1024))} KB</small></span><Button variant="outline" disabled={busy} onClick={()=>action(async()=>{if(await getAPI().restoreBackup(b.name)>=0)notify('Yedek geri yüklendi.');})}><RotateCcw/>Geri yükle</Button></div>)}{!backups.length&&<p className="muted">Henüz yedek yok.</p>}</div>
      </TabsContent>
      <TabsContent value="general" className="space-y-5"><h3>Bağlantılar ve hatırlatıcılar</h3><div className="setting-row"><div><strong>Arka planda bağlantı denetimi</strong><p>Bağlantılar günde bir denetlenir. 404 ve 410 yanıtları kırık, erişim engeli ve zaman aşımı belirsiz gösterilir.</p></div><label className="switch"><input type="checkbox" aria-label="Arka planda bağlantı denetimi" checked={settings?.linkChecker??true} disabled={busy||!settings} onChange={e=>action(()=>getAPI().setLinkChecker(e.target.checked))}/><span/></label></div><div className="flex flex-wrap gap-2"><Button variant="outline" disabled={busy} onClick={()=>action(async()=>{const r=await getAPI().checkLinks();notify(`${r.checked} bağlantı denetlendi, ${r.broken} kırık bağlantı bulundu.`);})}>Bağlantıları şimdi denetle</Button><Button variant="outline" disabled={busy} onClick={()=>action(()=>getAPI().testNotification(),'Deneme bildirimi Windows’a gönderildi.')}>Bildirimi dene</Button></div><p className="hint">Hatırlatıcılar uygulama açıkken çalışır. Kaçırılan tarihler sonraki açılışta bildirilir.</p><div className="settings-callout"><Info/><p>Saatin yanındaki DubBitig simgesinden pencereyi gizleyebilir, açabilir veya panodakini kaydedebilirsin. Pencereyi gizlediğinde hatırlatıcılar çalışmaya devam eder. Pencereyi kapattığında uygulama sistem tepsisine gizlenir; hatırlatıcılar ve yedekleme çalışmaya devam eder. Tamamen kapatmak için tepsi menüsünden Çıkış seç.</p></div><h3>Görünüm</h3><p className="muted">Sol menünün altındaki Açık / Koyu seçimiyle temayı değiştirebilirsin.</p></TabsContent>
      <TabsContent value="data" className="space-y-6"><section><h3>Veri konumu</h3><div className="data-location"><code>{settings?.dataPath??'Yükleniyor…'}</code><Button variant="ghost" size="icon" aria-label="Veri klasörünü aç" onClick={()=>action(()=>getAPI().openFolder('data'))}><FolderOpen/></Button></div><p className="hint">Standart konum: %APPDATA%\DubBitig. Kayıtlar, fotoğraflar ve yerel yedekler burada saklanır.</p></section><section><h3>İçeri ve dışarı aktar</h3><p className="muted">Tüm arşivi, seçilen kategorileri veya kayıt türlerini fotoğraflarıyla taşı.</p><div className="flex flex-wrap gap-2 mt-3"><Button variant="outline" disabled={busy} onClick={()=>transfer('export')}><Upload/>Dışarı aktar</Button><Button variant="outline" disabled={busy} onClick={()=>transfer('import')}><Download/>İçeri aktar</Button><Button variant="outline" disabled={busy} onClick={()=>action(async()=>{if(await getAPI().importArchive('replace')!==null)notify('Arşiv geri yüklendi.');})}><RotateCcw/>Dosyadan geri yükle</Button></div><p className="hint">Arşiv sınırı 512 MB. Yedekler şifrelenmez; bir kopyasını başka bir diskte saklayabilirsin.</p></section><section className="danger-zone"><h3>Bütün verileri sil</h3><p>Kayıtlar, çöp kutusu, sürüm geçmişi, fotoğraflar, kategoriler, etiketler, hatırlatıcılar, ayarlar ve bu klasördeki bütün yedekler kalıcı olarak silinir. Başka konumlara dışarı aktardığın dosyalar silinmez.</p><Button variant="destructive" disabled={busy} onClick={()=>{setPhrase('');setConfirm(true);}}><Trash2/>Bütün verileri sil</Button></section></TabsContent>
      <TabsContent value="about" className="space-y-6"><div className="flex items-center gap-5"><img src="./db.jpg" alt="DubBitig" className="size-20 rounded-2xl object-cover"/><div><h2 className="text-3xl font-semibold tracking-tight">DubBitig</h2><p className="text-muted-foreground mt-1">Kişisel bilgi arşivin</p><Badge variant="secondary" className="mt-2">Sürüm {settings?.version??'1.6.0'}</Badge></div></div><p className="about-lead">Hatırlamak istediğin bilgiyi tek bir yerde biriktir, düzenle ve ihtiyaç duyduğunda kolayca bul.</p><p className="muted">DubBitig; bilgisayar ve terminal komutlarını, kullandığın programları, web bağlantılarını, notlarını ve fotoğraflarını bilgisayarında saklamak için tasarlanmıştır. Kategoriler ve etiketlerle düzenler, aramayla bulur ve komutları tek tıkla kopyalarsın.</p><p className="muted">Markdown ile notlarını biçimlendirebilir, kodlarını sözdizimi vurgulamasıyla okuyabilir, geçmiş sürümlere dönebilir ve hatırlatıcılar ekleyebilirsin. Yedekleme ve kategori bazında içeri/dışarı aktarma, arşivini taşımana yardımcı olur.</p><div className="name-origin"><span>ADININ HİKÂYESİ</span><h3>Dub <b>+</b> Bitig</h3><p>Sümerce <strong>Dub (Tablet)</strong> ve Eski Türkçe <strong>Bitig (Yazı)</strong> sözcüklerinin birleşimidir. Bilgiyi kaydetme ve koruma fikrini taşır.</p></div><p className="hint">Veriler yerel olarak saklanır. Site önizlemesi ve bağlantı denetimi internet kullanır. Self-hosted/web senkronizasyonuna uygun servis ve adapter yapısı bulunur; bu sürümde senkronizasyon etkin değildir.</p></TabsContent>
    </Tabs>
    <Dialog open={confirm} onOpenChange={open=>{if(!busy)setConfirm(open);}}><DialogContent><DialogHeader><DialogTitle>Bütün veriler kalıcı olarak silinsin mi?</DialogTitle><DialogDescription>Yerel yedekler de silinecek. Bu işlem geri alınamaz. Devam etmek için BÜTÜN VERİLERİ SİL yaz.</DialogDescription></DialogHeader><Input aria-label="Silme onayı" autoComplete="off" value={phrase} onChange={e=>setPhrase(e.target.value)} disabled={busy}/><div className="flex justify-end gap-2"><Button variant="outline" disabled={busy} onClick={()=>setConfirm(false)}>Vazgeç</Button><Button variant="destructive" disabled={busy||phrase!=='BÜTÜN VERİLERİ SİL'} onClick={()=>action(async()=>{await getAPI().deleteAllData(phrase);await reset();setConfirm(false);},'Bütün yerel veriler silindi.')}>{busy?'Siliniyor…':'Kalıcı olarak sil'}</Button></div></DialogContent></Dialog>
  </DialogContent></Dialog>;
}
